# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1edc7241b36aa5ed5abbe15bfae006d3041e2bd7445a28f2a20d3726ca69e8e13111f211efd99979d9d54dcd20f3fca88665fc176bdf014cd7b99b61b0e63ba9

test:
  secret_key_base: 41de7c2be621557ed6b13e9229209c12d01a63f9881e15e9dbc9ad0a512739b624d778d3b8362b2ea4c1224ceccb642b620e43f4942b3886c8b0b3270707b9d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
